- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    xdg_config: "{{ lookup('env', 'HOME') }}/.config"
    repos: "/data/repos"
    git_ssh: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github_phnaharris"
  pre_tasks:
    - name: Run the equivalent of "pacman -Syu"
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        upgrade: true

  tasks:
    - name: Finding who I am?
      shell: whoami
      register: user
    - name: Finding where I am?
      shell: hostnamectl hostname
      register: hostname

    - include_tasks: tasks/install-ssh.yml
    - include_tasks: tasks/pull-repos.yml
    - include_tasks: tasks/install-paru.yml
