- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    xdg_config: "{{ lookup('env', 'HOME') }}/.config"
    repos: "/data/repos"
    dotfiles: "/data/repos/pmachos/dotfiles"
    git_ssh: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github_phnaharris"
  pre_tasks:
    - name: Run the equivalent of "pacman -Syu"
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        upgrade: true

  tasks:
    - name: Finding who I am?
      shell: whoami
      register: user
    - name: Finding where I am?
      shell: hostnamectl hostname
      register: hostname

  tasks:
    - import_tasks: tasks/install-ssh.yml
    - import_tasks: tasks/pull-repos.yml
    - import_tasks: tasks/install-paru.yml
    - import_tasks: tasks/install-hardware-driver.yml
    - import_tasks: tasks/install-util-apps.yml
    - import_tasks: tasks/install-server.yml
    - import_tasks: tasks/install-latex.yml
      tags:
        - latex
    - import_tasks: tasks/install-gui.yml
    - import_tasks: tasks/enable-systemd.yml
