- name: Make sure directory existed
  file:
    dest: "{{ repos }}"
    mode: 0700
    state: directory

- name: Make sure orgs/user directory existed
  file:
    dest: "{{ repos }}/{{ item }}"
    mode: 0700
    state: directory
  loop:
    - phnaharris
    - pmachos

- name: Pulling repos
  vars:
    gituser:
      - name: "phnaharris"
        repositories:
          - phnaharris.github.io
          - dotfiles
          - passwords
          - scripts
          - wireguard-vpns
  git:
    repo: "git@github.com:{{ item.0.name }}/{{ item.1 }}.git"
    dest: "{{ repos }}/{{ item.0.name }}/{{ item.1 }}"
    key_file: "{{ git_ssh }}"
    accept_hostkey: yes
    clone: yes
    update: yes
  loop: "{{ gituser|subelements('repositories') }}"
  loop_control:
    label: "{{ item.0.name }}"
